name: twitter_ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  auth_buttons: ^3.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  flutter_riverpod: ^2.4.10
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  hidable: ^1.0.6
  http: ^1.2.0
  intl: ^0.18.1
  lottie: ^3.1.0
  path: ^1.8.3
  path_provider: ^2.0.5
  riverpod_annotation: ^2.3.4
  sign_in_button: ^3.2.0
  sqflite: ^2.3.2
  sqflite_common_ffi: any
  sqflite_common_ffi_web: '>=0.1.0-dev.1'
  toastification: ^1.2.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/twitter-black.png"

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#202124"
  image: "assets/twitter.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/


